_BASE_: "../../../base-prompt_changed_P_VK_ssl_mae.yaml"
RUN_N_TIMES: 1
DATA:
  NAME: "StanfordDogs"
  DATAPATH: "/shared/kgcoe-research/spl/fgvc/Stanford-dogs"  #TODO: need to specify here
  NUMBER_CLASSES: 120
  MULTILABEL: False
MODEL:
  TYPE: "ssl-vit"
SOLVER:
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.0001