_BASE_: "../../../../base-prompt_changed_P_VK.yaml"
RUN_N_TIMES: 1
DATA:
  NAME: "vtab-dtd"
  DATAPATH: "/shared/kgcoe-research/spl/VTAB-1k/Natural/"  #TODO: need to specify here
  NUMBER_CLASSES: 47
  MULTILABEL: False
MODEL:
  TYPE: "vit"
SOLVER:
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.001
