_BASE_: "../../../base-prompt.yaml"
RUN_N_TIMES: 1
DATA:
  NAME: vtab-clevr(task="count_all")
  DATAPATH: "/shared/kgcoe-research/spl/VTAB-1k/Structured/"  #TODO: need to specify here
  NUMBER_CLASSES: 8
  MULTILABEL: False
MODEL:
  TYPE: "vit"
SOLVER:
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.001
