_BASE_: "../../../../base-prompt_changed_P_VK_swin.yaml"
RUN_N_TIMES: 1
DATA:
  NAME: "vtab-oxford_flowers102"
  DATAPATH: "/shared/kgcoe-research/spl/VTAB-1k/Natural/"  #TODO: need to specify here
  NUMBER_CLASSES: 102
  MULTILABEL: False
MODEL:
  TYPE: "swin"
SOLVER:
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.001
