_BASE_: "../../../base-prompt_changed_P_VK_swin.yaml"
RUN_N_TIMES: 1
DATA:
  NAME: "StanfordCars"
  DATAPATH: "/shared/kgcoe-research/spl/fgvc/Stanford-cars"  #TODO: need to specify here
  NUMBER_CLASSES: 196
  MULTILABEL: False
MODEL:
  TYPE: "swin"
SOLVER:
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.001
