_BASE_: "../../../base-finetune.yaml"
RUN_N_TIMES: 1
DATA:
  NAME: "vtab-oxford_iiit_pet"
  DATAPATH: "/shared/kgcoe-research/spl/VTAB-1k/Natural/"  #TODO: need to specify here
  NUMBER_CLASSES: 37
  MULTILABEL: False
MODEL:
  TYPE: "vit"
SOLVER:
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.001
