NUM_GPUS: 1
NUM_SHARDS: 1
OUTPUT_DIR: "output"
RUN_N_TIMES: 1
MODEL:
  TRANSFER_TYPE: "P_VK" # set transfer type here # SELF_QKV+bias
  TYPE: "swin"
  LINEAR:
    MLP_SIZES: []
SOLVER:
  SCHEDULER: "cosine"
  PATIENCE: 300
  LOSS: "softmax"
  OPTIMIZER: "sgd"
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0001
  LOG_EVERY_N: 100 #100
  WARMUP_EPOCH: 10 # 10
  TOTAL_EPOCH: 100 #100
DATA:
  NAME: "test"
  NUMBER_CLASSES: -1
  DATAPATH: ""
  FEATURE: "swinb_imagenet22k_224"
  BATCH_SIZE: 80
