_BASE_: "../../../../base-prompt_changed_P_VK_ssl_moco.yaml"
RUN_N_TIMES: 1
DATA:
  NAME: "vtab-patch_camelyon"
  DATAPATH: "/shared/kgcoe-research/spl/VTAB-1k/Specialized/"  #TODO: need to specify here
  NUMBER_CLASSES: 2
  MULTILABEL: False
MODEL:
  TYPE: "ssl-vit"
SOLVER:
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.001
